### ISSUE TITLE
feat(gui): improve the current MedQA Assistant GUI

### ISSUE THREAD

**Issue by mratanusarkar** [soumik12345/medrag-multi-modal#26]
carry forwards from #25 

- [x] improve 3 "model selector" dropdown(s) options in GUI for multimodal and text-only modal usage.
- [x] deploy/host the streamlit app somewhere?
- [x] enhance the GUI.
- [ ] implement history in the `MedCPTRetriever` and make the GUI into a conversational chat flow.

**Comment by soumik12345** [comment]
> implement history in the MedCPTRetriever and make the GUI into a conversational chat flow.

Is being tracked as part of #47 

Rest were addressed in #38
